"""
Report Generator — Produce professional Markdown intelligence briefs.

Converts agent output (search results + AI analysis + embeddings + audit trail)
into structured, readable reports for bounty submission.
"""

import logging
from datetime import datetime, timezone
from typing import Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate Markdown intelligence reports from agent output."""

    def __init__(self, output_dir: Path = Path("examples")):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, result) -> str:
        """Generate a complete intelligence report from an IntelligenceResult.

        Args:
            result: IntelligenceResult from the engine run

        Returns:
            Path to the generated report file
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
        safe_topic = "".join(c if c.isalnum() else "-" for c in result.query)[:40]
        filename = f"intel-brief-{safe_topic}-{timestamp}.md"
        filepath = self.output_dir / filename

        lines = [
            f"# 🔮 Atlas Nexus Intelligence Brief",
            f"",
            f"**Topic**: {result.query}",
            f"**Generated**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Agent**: Autonomous Data Intelligence Agent — OOBE Synapse × Ace Data Cloud",
            f"**Bounty**: OOBE × Ace Data Cloud Autonomous Agent Bounty (Category 2)",
            f"",
            f"---",
            f"",
            f"## 🧠 AI Analysis",
            f"",
            result.ai_analysis,
            f"",
        ]

        if result.visualization_url:
            lines.extend([
                f"---",
                f"",
                f"## 🎨 Visualization",
                f"",
                f"![Generated visualization]({result.visualization_url})",
                f"",
            ])

        # Embeddings info
        if result.embedding_dim:
            lines.extend([
                f"---",
                f"",
                f"## 🧬 Semantic Embeddings",
                f"",
                f"- **Model**: text-embedding-3-small",
                f"- **Dimensions**: {result.embedding_dim}",
                f"- **Purpose**: Semantic indexing of intelligence output for future retrieval",
                f"",
            ])

        # Execution audit trail
        lines.extend([
            f"---",
            f"",
            f"## 🔍 Execution Audit",
            f"",
            f"### Services Used (Ace Data Cloud via x402)",
            f"",
            *[f"- ✅ **{svc}** — Ace Data Cloud API" for svc in result.services_used],
            f"",
            f"### Payment Summary",
            f"",
            f"- **Total USDC spent**: ${result.total_cost_usdc:.6f}",
            f"- **Payment protocol**: x402 (Solana USDC)",
            f"- **Payment handler**: acedatacloud-x402",
            f"",
            f"### Bounty Compliance (Category 2 — Ace Data Cloud Usage)",
            f"",
            f"- ✅ 3 distinct Ace Data Cloud services: {', '.join(result.services_used)}",
            f"- ✅ x402 with AceDataCloud payment facilitator",
            f"- ✅ Synapse RPC integration",
            f"- ✅ Complete automated workflow (trigger → execution → payment)",
            f"",
            f"### Run Log",
            f"",
            *[f"- {entry}" for entry in result.run_log],
            f"",
            f"---",
            f"",
            f"*Autonomously generated by Atlas Nexus Data Intelligence Agent*",
            f"*Powered by OOBE Protocol Synapse × Ace Data Cloud × x402 × Solana*",
        ])

        report = "\n".join(lines)
        filepath.write_text(report)
        logger.info(f"📄 Report generated: {filepath}")
        return str(filepath)
